#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavBarTestAndroid.Resource", IsApplication=true)]

namespace NavBarTestAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ActionComponents.Resource.String.library_name = global::NavBarTestAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barchart = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gear = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int house = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Linen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int orgchart = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int printer = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ticket = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int trash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int view1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int view2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int view3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int view4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int view5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int warning = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int masterLayout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int navBar = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int relativeLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int showHideButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int viewBarChart = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int viewHome = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ViewBarChart = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ViewOrgChart = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewSettings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewTIcket = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
